### ISSUE TITLE
Produce GenericPackageDescriptions

### ISSUE THREAD

**Issue by ocharles** [ocharles/dhall-to-cabal#2]
Step two is to produce GenericPackageDescriptions. My thought here is to introduce variables like `os` into the typing environment, but keep them as free variables and block normalization. We normalize as far as we can, and then I can reflect underlying `if` expressions from Dhall to `CondTree` expressions in the Cabal file.

Thus, we would be writing

```
build-dependencies = [ ... ] ++ if os == Linux then [ ... ] else [ ... ]
```

to get

```cabal
build-depends:
  ...
  if os(linux):
    ...
```

(or whatever the valid cabal syntax is)

@Gabriel439, does this sound sensible?

**Comment by Gabriel439** [comment]
Yeah, if this is going to be its own command-line executable then the most user-friendly approach is to use `loadWith`, `typeWith` and `normalizeWith` to bring additional free variables into scope

**Comment by ocharles** [comment]
I'm not sure how to best approach this. My first thought was to change

```dhall
{ ..., library : ./types/Library, ... }
```

Into

```dhall
{ ..., library : OS -> ./Types/Library
```

That is, the `library` field now becomes a function of `OS` to build information.

In order to use native `if` syntax, we need some way to move from `OS` to `Bool`, so lets assume my environment also gives me `isLinux : OS -> Bool`. At this point I could write

```
library = \(os : OS) -> { buildDepends = if isLinux os then [ posix ] else [] }
```

or something, which is lovely.

If all usage of the `Bool` derived from `os` is within `If` statements then things are (I think OK). Thinks become much more problematic if I do

```
library = \(os : OS) -> { buildable = isLinux os }
```

as it's now much harder to see that `os` is being used in a condition.

It seems like I would want to rewrite this expression to 

```
library = \(os : OS) -> { buildable = if isLinux os then True else False }
```

and I'm back to the scenario where all usage of `os` are within `if` conditions.

---

On the Cabal side of things, all configuration is through the [`CondTree`](https://hackage.haskell.org/package/Cabal-2.0.1.1/docs/Distribution-Types-CondTree.html#t:CondTree) data type. My plan was roughly to have

```haskell
condTree :: Dhall.Type a -> Dhall.Type (CondTree ConfVar c a)
```

to lift a `Dhall.Type` parser such that I transform `BoolIf` `Expr`s into `CondBranch`s.

@Gabriel439 Does my above rambling make any sense? Is it a sensible way to add Cabal's `if` feature?

**Comment by Gabriel439** [comment]
The `if isLinux os then True else False` trick will not work.  The [standard semantics](https://github.com/dhall-lang/dhall-lang/blob/master/standard/semantics.md#bool) specifies:

>  Also, simplify an `if` expression if the expression trivially returns the
predicate:
>
>
>     l ⇥ True   r ⇥ False   t₀ ⇥ t₁
>     ──────────────────────────────
>     if t₀ then l else r ⇥ t₁

... which is just a formal way of saying that `if b then True else False` has to normalize to `b`.

Note that the Haskell implementation actually does not do this yet (I forgot to update it when standardizing the semantics, and just realized that while typing this comment).

I think the best (but hardest-to-implement) approach is to translate Dhall programming language features intelligently to Cabal and to embed the primitive operations directly in Dhall instead of assuming them as free variables from the context.

For example, implement the `OS` type as a Dhall union type:

```haskell
    let OperatingSystem = < Linux : {} | Darwin : {} >

in  let OS = constructors OperatingSystem

in  ...
```

... and give the `library` field the type `OperatingSystem -> ./types/Library` like you proposed.  Then if the `dhall-to-cabal` compiler sees an expression like:

```haskell
  λ(os : OperatingSystem)
→ merge
  { Linux  = λ(_ : {}) → library₀
  , Darwin = λ(_ : {}) → library₁
  }
```

... it generates this `.cabal` stanza:

```cabal
library:
  if os(linux):
    library₀
  if os(darwin):
    library₁
```

I the second best (and easiest) approach is to just say that `dhall-to-cabal` doesn't support `cabal` conditional stanzas, pull requests welcome.  :)  Most users would be fine with that.

**Comment by ocharles** [comment]
I don't think your approach will scale unfortunately, as I can't see how I would express the harder conditions such as GHC version ranges, where I don't have a fixed size enumeration. Also, nesting constraints seems difficult:


```
if os(linux):
  if !impl(ghc>=7.9)
    ..
```

etc.

However, what I *think* works and is actually fairly manageable syntactically is changing the type of the `library` (and other conditional fields) to:

```
library : List ({ guard : Options-> Bool, library : Library })
```

This seems a little simpler than the `merge` approach. Your above example would be:

```dhall
[ { guard = linuxOnly, library = library₀ }
, { guard = darwinOnly, library = library₁ }
]
```

or perhaps

```dhall
    let OperatingSystem = < Linux : {} | Darwin : {} >

in  let OS = constructors OperatingSystem

in  [ { guard = on (OS.Linux {=}), library = library₀ }
    , { guard = on (OS.Darwin {=}), library = library₁ }
    ]
```

**Comment by Gabriel439** [comment]
For either approach, you will want to add a new-builtin to comparing against the GHC version:

```haskell
-- ghcNewerThan : List Natural → Bool

  let not = λ(b : Bool) → b != False

in    λ(os : OperatingSystem)
    → merge
      { Linux  = λ(_ : {}) → if not (ghcNewerThan [ +7, +9 ]) then library₀ else library₁
      , Darwin = λ(_ : {}) → library₂
      }
      os
```

Then when normalizing the syntax tree any time you see an `if` in an appropriate place you also translate that to a `.cabal` `if` and if you see `!= False` (the normalized version of `not`), you translate that to `!` (assuming that `.cabal` files don't have built-in support for `!=` or `False`; I don't know how expressive the `.cabal` language is)

The issue with expecting a list of guards in the schema is that `.cabal` files let you mix predicates and stanza lines.  For example, I believe this is legal:

```
build-depends:
  line₀
  if predicate₀:
    line₁
    if predicate₁:
      line₂
```

... which means that your schema would have to expect a list of guards anywhere that an `if` expression was legal and your schema would have to support a recursively nested list of guards.

However, that doesn't mean that you can't have a list of guards, but rather that it shouldn't be part of the `.cabal` file schema.  You can still create a `guards` function within the Dhall language that accepts your preferred guard syntax, like this:

```haskell
    let guards
        :   ∀(a : Type)
          → ∀(branches : List { guard : Bool, value : a })
          → ∀(fallback : a)
          → a
        =   λ(a : Type)
          → λ(xs : List { guard : Bool, value : a })
          → λ(fallback : a)
          → List/fold
            { guard : Bool, value : a }
            xs
            a
            (   λ(x : { guard : Bool, value : a })
              → λ(result : a)
              → if x.guard then x.value else result
            )
            fallback

in  guards
```

... and then you could write:

```haskell
guards Library
  [ { guard = linuxOnly  os, value = library₀ }
  , { guard = darwinOnly os, value = library₁ }
  ]
  library₂
```

... and that would support nesting without any changes to the schema:

```haskell
guards Library
  [ { guard = linuxOnly os, value = guards Library
      [ { guard = ghcNewerThan [ +7, +9 ] library₀ } ]
      library₁
    }
  , { guard = darwinOnly os, value = library₂ }
  ]
  library₃
```

More generally, the rule of thumb I would go by is that `.cabal` programming language features should not be part of the Dhall schema for a `.cabal` file, otherwise the schema will grow pretty complicated.  Instead they should just be encoded as Dhall logic or new built-ins (if they are clumsy or impossible to express in the Dhall language) and then translated to the matching `.cabal` language feature.

Here's a simple example tying some of these ideas together (with some minor simplifications for the example):

```
  λ(Library : Type)
→ λ(library0 : Library)
→ λ(library1 : Library)
→ λ(library2 : Library)
→ λ(library3 : Library)
→ λ(linux : Bool)
→ λ(darwin : Bool)
→ λ(ghcNewerThan : List Natural → Bool)
→     let guards
          :   ∀(a : Type)
            → ∀(branches : List { guard : Bool, value : a })
            → ∀(fallback : a)
            → a
          =   λ(a : Type)
            → λ(xs : List { guard : Bool, value : a })
            → λ(fallback : a)
            → List/fold
              { guard : Bool, value : a }
              xs
              a
              (   λ(x : { guard : Bool, value : a })
                → λ(result : a)
                → if x.guard then x.value else result
              )
              fallback
  
  in  guards
      Library
      [ { guard = linux
        , value =
            guards
            Library
            [ { guard = ghcNewerThan [ +7, +9 ], value = library0 } ]
            library1
        }
      , { guard = darwin, value = library2 }
      ]
      library3
```

... and if you normalize that, you get:

```
  λ(Library : Type)
→ λ(library0 : Library)
→ λ(library1 : Library)
→ λ(library2 : Library)
→ λ(library3 : Library)
→ λ(linux : Bool)
→ λ(darwin : Bool)
→ λ(ghcNewerThan : List Natural → Bool)
→       if linux then if ghcNewerThan [ +7, +9 ] then library0 else library1
  
  else  if darwin then library2
  
  else  library3
```

... which is exactly the nested `if` expression one might write by hand if not using the `guards` function

**Comment by ocharles** [comment]
> The issue with expecting a list of guards in the schema is that .cabal files let you mix predicates and stanza lines. For example, I believe this is legal:
>
> ```
> build-depends:
>  line₀
>  if predicate₀:
>    line₁
>    if predicate₁:
>      line₂
>
> ... which means that your schema would have to expect a list of guards anywhere that an if expression was legal and your schema would have to support a recursively nested list of guards.

It is, but that is still expressible with a list of guards:

```
build-depends:
  line0
  if predicate0:
    line1
  if predicate0 and predicate1:
    line2
```

Anyway, the main reason I suggested the `List { guard : Predicates -> Bool, library : Library }` approach is because it means I can restrict introducing `Bool` valued predicates to only be present in the guard branch. As above, if `isLinux` is in scope in the `Library`, then compiling something like `{ buildable = isLinux }` is much harder. Right now, `buildable` is simply extracted with `Dhall.bool`. I can't quite see, but doesn't your approach have the same problem? Could you express your proposal in an expression that has type `{ buildable : Bool, buildDepends : List Text }` (or more, extend that type with what you need. Let's assume that's a simplification of the type accepted by `dhall-to-cabal`).

**Comment by Gabriel439** [comment]
One thing I want to point out is that instead of providing:

```haskell
currentOperatingSystem : OS

isLinux : OS → Bool

isDarwin : OS → Bool
```

It might be simpler to just provide:

```haskell
isLinux : Bool

isDarwin : Bool
```

Then you would have:

```
{ buildable  = isLinux }
```

... and on a Linux platform that would evaluate to:

```haskell
{ buildable = True }
```

... which you could easily marshal into Haskell without having to compile a function

**Comment by ocharles** [comment]
But that's saying `dhall-to-cabal` shouldn't even bother with conditionals, and now it starts to actually have Cabal's semantics. That's not really the goal here - the goal is to just produce Cabal files. I think I've missed something in this discussion.

**Comment by Gabriel439** [comment]
Oh, sorry, that's right.  `dhall-to-cabal` can't know at compile time what operating system the package will be built on.

However, I still think that `isLinux` and `isDarwin` should have type `Bool` for simplicity.  They just can't be replaced with an actual concrete `True` or `False` when compiling the file to `.cabal` format

**Comment by ocharles** [comment]
But they can't be replaced with a bool, that's the problem :smile: 

If you write

```
buildable = isLinux
```

I have to compile that into

````
if os(linux):
  buildable: True
if not os(linux):
  buildable: False
```

So the extraction becomes considerably more complex. This happens through *all* fields in `Library`.

I think having a list of libraries with guards might be the best way to control this.

**Comment by Gabriel439** [comment]
I think it's better to make the translation process more complicated than to make the schema more complicated.  I'm totally fine with `isLinux` expanding out to the more complex `.cabal` format.  That's something that I would expect a compiler to do for the user when the target language is restricted and this is essentially a compiler.

**Comment by ocharles** [comment]
Mmmm. Alright, so I think this is basically the approach I suggested in https://github.com/ocharles/dhall-to-cabal/issues/2#issuecomment-359975332. I can't provide `isLinux` over the whole expression, but I could supply it as a function argument to `Library`. I say this because

```
copyright = if isLinux then ... else ...
```

can't be compiled, but would apparently type-check.

**Comment by ocharles** [comment]
`ConfVar` is the set of configuration options, btw: https://hackage.haskell.org/package/Cabal-2.0.1.1/docs/Distribution-Types-GenericPackageDescription.html#t:ConfVar.

**Comment by Gabriel439** [comment]
Note that it's normal for a compiler to reject things that type-check.  For example, the `dhall-to-json` compiler will reject a well-typed function just because there's no way to encode functions in JSON and `dhall-to-nix` rejects floating point numbers for the same reason (although I believe newer versions of Nix now support floats so I need to fix that).  Your compiler function should have a place to hold errors specific to translation to Cabal, similar to this:

https://hackage.haskell.org/package/dhall-nix-1.0.10/docs/Dhall-Nix.html#t:CompileError

So you could in principle have an error that essentially says that `isLinux` or `isDarwin` are only supported in certain configuration sections

However, that said, I think you are still right and the schema should reflect the fact that only certain schema sections of the schema can be configured on a per-operating system basis.  That way a user can tell from reading the schema which parts are configurable on a per-operating system basis instead of having to play guess and check with compiler errors.

So I take back my suggestion and think you should do something like the guards.

**Comment by Gabriel439** [comment]
Also, I agree that for the guards route you can side-step the need for nested guards by flattening the predicates, so I think that resolves my other concern.

**Comment by ocharles** [comment]
Alright, I've taken a stab at the guards approach. You can now write this:

```haskell
  ./dhall/empty-package.dhall 
⫽ { library =
      [ [ { body  =
                ./dhall/defaults/Library.dhall 
              ⫽ { buildable = False, exposed-modules = [ "Bar" ] }
          , guard = λ(os : < Linux : {} >) → False
          }
        , { body  =
              ./dhall/defaults/Library.dhall  ⫽ { exposed-modules = [ "Foo" ] }
          , guard = λ(os : < Linux : {} >) → True
          }
        , { body  =
                ./dhall/defaults/Library.dhall 
              ⫽ { exposed-modules = [ "Hello" ] }
          , guard = λ(os : < Linux : {} >) → True
          }
        ]
      ] : Optional (./dhall/types/Guarded  ./dhall/types/Library )
  , package = { name = "test", version = [ +1 ] }
  }
```

Which generates this

```
name: test
version: 1
cabal-version: 2.0
build-type: Simple
license: UnspecifiedLicense

library
    
    if False
        exposed-modules:
            Bar
        buildable: False
    exposed-modules:
        Foo
        Hello
```

I need to complete https://github.com/ocharles/dhall-to-cabal/blob/d7ad78df7f98ba5a74bf001f3f826eb62af01a27/lib/Distribution/Package/Dhall.hs#L1084 next, which parses an individual guard.

Does this look OK so far?

**Comment by Gabriel439** [comment]
Yeah, I like the idea of a record with a `library` and `guard` field.  The only suggestions I can think of at the moment are:

* possibly renaming the `guard` field to `condition`
* Instead of an anonymous function of an operating system, just add built-in values named `isLinux` and `isDarwin` which would have type `Bool` but not evaluate to anything

**Comment by ocharles** [comment]
> possibly renaming the guard field to condition 

I don't mind that. I could also use ``if``

> Instead of an anonymous function of an operating system, just add built-in values named isLinux and isDarwin which would have type Bool but not evaluate to anything


I don't think this is possible, because `isLinux` can only occur within a `library` stanza. That is, the following:

```haskell
  ./dhall/empty-package.dhall 
⫽ { package = { name = if isLinux then "test1" else "test2", version = [ +1 ] }
  }
```

type checks but cannot be compiled. I'm not sure I like that, but it could be done (as you say, `dhall-to-cabal` can have its own compilation failures).

If I use the anonymous function approach, I don't have that problem, at the cost of slightly more syntax.

**Comment by Gabriel439** [comment]
Oh yeah, I keep forgetting that `isLinux` is not globally valid within the configuration file.  In that case I think the way you have it is the correct approach.

Note that if you name the field `if` you would have to escape the field name with backticks because `if` is a reserved keyword.

**Comment by ocharles** [comment]
Oh, GitHub ate my formatting, I did use extra `s to try and be sure!

Awesome, I'll crack on with this approach - hopefully get this issue closed out soon.

**Comment by ocharles** [comment]
Ok, I believe this is done now. The following completely contrived example...

```
    let OS = constructors ./dhall/types/OS 

in  let Arch = constructors ./dhall/types/Arch 

in  let Compiler = constructors ./dhall/types/Compiler 

in    ./dhall/empty-package.dhall 
    ⫽ { library =
          [ [ { body =
                    ./dhall/defaults/Library.dhall 
                  ⫽ { buildable = False, exposed-modules = [ "Bar" ] }
              , guard =
                    λ(config : ./dhall/types/Config )
                  →     config.os (OS.Linux {=}) == config.arch (Arch.Mips {=})
                    &&  (       if    config.os (OS.Linux {=})
                                then  config.arch (Arch.X86_64 {=})
                          
                          else  config.arch (Arch.PPC {=})
                        )
              }
            , { body =
                    ./dhall/defaults/Library.dhall 
                  ⫽ { exposed-modules = [ "Foo" ] }
              , guard =
                    λ(config : ./dhall/types/Config )
                  →     config.arch (Arch.Mips {=})
                    &&  config.impl
                        (Compiler.GHC {=})
                        (majorBoundVersion [ +8, +2 ])
              }
            , { body =
                    ./dhall/defaults/Library.dhall 
                  ⫽ { exposed-modules = [ "Hello" ] }
              , guard =
                  λ(config : ./dhall/types/Config ) → config.os (OS.Linux {=})
              }
            ]
          ] : Optional (./dhall/types/Guarded  ./dhall/types/Library )
      , package =
          { name = "test", version = [ +1 ] }
      }
```

Produces

```
name: test
version: 1
cabal-version: 2.0
build-type: Simple
license: UnspecifiedLicense

library
    
    if (((os(linux) && arch(mips)) || (!os(linux) && !arch(mips))) && ((os(linux) && arch(x86_64)) || (!os(linux) && arch(ppc))))
        exposed-modules:
            Bar
        buildable: False
    
    if (arch(mips) && impl(ghc ^>=8.2))
        exposed-modules:
            Foo
    
    if os(linux)
        exposed-modules:
            Hello
```

Which I *think* is correct. We've ended up with `guard` having type

```
{ os :
    ./OS  → Bool
, arch :
    ./Arch  → Bool
, impl :
    ./Compiler  → VersionRange → Bool
} → Bool
```
